# Generated by Django 4.2.30 on 2026-05-24 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.BigIntegerField(blank=True, help_text='ID de usuario en tabla TypeORM', null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('presupuesto_max', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('tipo_prop_pref', models.CharField(blank=True, max_length=50)),
                ('habitaciones_pref', models.IntegerField(blank=True, null=True)),
                ('zona_pref', models.CharField(blank=True, max_length=100)),
                ('n_busquedas', models.IntegerField(default=0)),
                ('interacciones', models.IntegerField(default=0)),
                ('segmento_id', models.IntegerField(blank=True, null=True)),
                ('segmento_nombre', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clients_client',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('propiedad_id', models.BigIntegerField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='clients.client')),
            ],
            options={
                'db_table': 'clients_clientrecommendation',
                'ordering': ['-score'],
            },
        ),
    ]
