# Generated by Django 4.2.30 on 2026-05-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propiedad_id', models.BigIntegerField(blank=True, help_text='ID de la tabla propiedad (TypeORM)', null=True)),
                ('input_data', models.JSONField()),
                ('precio_estimado', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('rango_min', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('rango_max', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('done', 'Listo'), ('failed', 'Fallido')], default='pending', max_length=10)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'valuations_valuationjob',
                'ordering': ['-created_at'],
            },
        ),
    ]
