# Generated by Django 4.2.30 on 2026-05-24 13:57

import apps.image_analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propiedad_id', models.BigIntegerField(help_text='ID de propiedad en tabla TypeORM')),
                ('image', models.ImageField(upload_to=apps.image_analysis.models.image_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('done', 'Listo'), ('failed', 'Fallido')], default='pending', max_length=15)),
                ('conservation_state', models.CharField(blank=True, choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deteriorado', 'Deteriorado'), ('Ruinoso', 'Ruinoso')], max_length=20, null=True)),
                ('room_type', models.CharField(blank=True, choices=[('Sala', 'Sala'), ('Cocina', 'Cocina'), ('Dormitorio', 'Dormitorio'), ('Bano', 'Baño'), ('Exterior', 'Exterior'), ('Garaje', 'Garaje'), ('Terraza', 'Terraza'), ('Otro', 'Otro')], max_length=20, null=True)),
                ('confidence_conservation', models.FloatField(blank=True, null=True)),
                ('confidence_room', models.FloatField(blank=True, null=True)),
                ('full_result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.BigIntegerField(blank=True, help_text='ID usuario (TypeORM)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'image_analysis_propertyimage',
                'ordering': ['-created_at'],
            },
        ),
    ]
